name: Docs to PDF
on: push
jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: img/2023
          output_dir: img/2023/pdf
          build_html: false
      - uses: actions/upload-artifact@v1
        with:
          name: test.pdf
          path: img/2023/pdf